import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body>
    <Navbar/>
    <div className="bg-white text-black min-h-screen flex flex-col">
      {children}
    </div>
    </body>
    </html>
  );
}
