import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <div className="bg-amber-500 text-yellow-50 min-h-screen flex flex-col">
      <header className="p-4 text-center">Header</header>
      <main className="flex-1 p-4">{children}</main>
      <footer className="p-4 text-center">Footer</footer>
    </div>
    </html>
  );
}
